version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    networks:
      - mega_ofertas_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - mega_ofertas_network

networks:
  mega_ofertas_network:
    driver: bridge
