version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - PGDATABASE=railway
      - PGUSER=postgres
      - PGPASSWORD=EWoIZJyqFiHUhvNUmImFUgVSxMlUIMTs
      - PGHOST=postgres.railway.internal
      - PGPORT=5432
      - JWT_SECRET=ZJ%73@kM!xF4Wv9r$tN&2P6Q1u8HpXa*YdLgT#5C^BzV7JwR
      - JWT_EXPIRES_IN=24h
      - MP_ACCESS_TOKEN=TEST-5972548390104146-020518-94a1fafb2c39214492ca9ee1dc2f3f34-157704548
    networks:
      - mega_ofertas_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - mega_ofertas_network

networks:
  mega_ofertas_network:
    driver: bridge
